// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwycpFAvL0lyqO8WMllMTLVG9ZBWXeb4o',
    appId: '1:706194773055:web:a95899c526ac68d9ad948a',
    messagingSenderId: '706194773055',
    projectId: 'barbek-f1c69',
    authDomain: 'barbek-f1c69.firebaseapp.com',
    storageBucket: 'barbek-f1c69.firebasestorage.app',
    measurementId: 'G-ZWSR19WMYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn5QJQv1n6_hITpcpHwqK2zxbCEkMCS7c',
    appId: '1:706194773055:android:0954cee4cda31e19ad948a',
    messagingSenderId: '706194773055',
    projectId: 'barbek-f1c69',
    storageBucket: 'barbek-f1c69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSSTJkVs00twhjF2ubh5FmA6fCp2NHdRI',
    appId: '1:706194773055:ios:3e4d91780f97d938ad948a',
    messagingSenderId: '706194773055',
    projectId: 'barbek-f1c69',
    storageBucket: 'barbek-f1c69.firebasestorage.app',
    iosBundleId: 'com.example.projectKel5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSSTJkVs00twhjF2ubh5FmA6fCp2NHdRI',
    appId: '1:706194773055:ios:3e4d91780f97d938ad948a',
    messagingSenderId: '706194773055',
    projectId: 'barbek-f1c69',
    storageBucket: 'barbek-f1c69.firebasestorage.app',
    iosClientId: 'YOUR-MACOS-CLIENT-ID',
    iosBundleId: 'com.example.projectKel5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwycpFAvL0lyqO8WMllMTLVG9ZBWXeb4o',
    appId: '1:706194773055:web:fbf46b61a890ac5bad948a',
    messagingSenderId: '706194773055',
    projectId: 'barbek-f1c69',
    authDomain: 'barbek-f1c69.firebaseapp.com',
    storageBucket: 'barbek-f1c69.firebasestorage.app',
    measurementId: 'G-62823VQL2Z',
  );

}