// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlME9GdhNxyG1XEj2o1qaDE2JCmO-BmVM',
    appId: '1:560073040051:web:083276bb2b7cfa935250c6',
    messagingSenderId: '560073040051',
    projectId: 'barbek-9f083',
    authDomain: 'barbek-9f083.firebaseapp.com',
    storageBucket: 'barbek-9f083.firebasestorage.app',
    measurementId: 'G-QQ8Q0WGDTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAlmUI9hBXNNGmBC5IM2AfH0HKf6zgwDE',
    appId: '1:560073040051:android:06e439082bcbb21e5250c6',
    messagingSenderId: '560073040051',
    projectId: 'barbek-9f083',
    storageBucket: 'barbek-9f083.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCnKI09M6SAvqLESEHvPiGqXCqD41ZSD0',
    appId: '1:560073040051:ios:faaa5c2273aeb84e5250c6',
    messagingSenderId: '560073040051',
    projectId: 'barbek-9f083',
    storageBucket: 'barbek-9f083.firebasestorage.app',
    iosBundleId: 'com.example.projectKel5',
  );

}